### PR TITLE
Multibyte characters matching fixed

### PR DESCRIPTION
**Pull request by hranicka**
On system where UTF-8 is not default mb_internal_encoding charset there were some problems with inflection.

Eg. I've get `It\xe3\xa1liei` instead of `It\xe3\xa1lii` (UTF-8: Itálie -> Itálii).

So I've made fixes & added .gitignore & updated composer requirements for dev.

### CODE REVIEW

**Comment by Mikulas** [comment]
Thanks, but I'm hesitant to merge this. It's kind of unwritten rule now all code is utf8, isn't it? Even if somebody is so unfortunate to work on a legacy nonutf8 system, it seems it would be better to create a decorator that would set internal encoding and reset it after the call. That would remove clutter from the actual method calls and would still perform fine.

**Comment by hranicka** [comment]
Default multibyte internal encoding (for mbstring functions) is:
- ISO-8859-1 for PHP <= 5.5
- UTF-8 for PHP >= 5.6

See http://3v4l.org/qToNH

If server runs on PHP lower 5.6 and if it's not explicity set `mb_internal_encoding('UTF-8')`, code hasn't worked well.

## 

On some places in the code it has already been "charset" parameter set for mb_\* functions:
- https://github.com/Mikulas/inflection/blob/master/src/Inflection.php#L532
- https://github.com/Mikulas/inflection/blob/master/src/Inflection.php#L575

I've only added it also for other mb_\* functions and added tests for the charset issue.
There were used also singlebyte functions in the Inflection::match method before so I've changed this too.

**Comment by fprochazka** [comment]
Imho you should work with utf8 only and if you don't have that, just iconv it.

**Comment by hrach** [comment]
Guys (probably more Filip, whose comment seems to be ingoring this fact), you are both right, that using UTF-8 is requirement. But, I care how a library works. I have no idea it uses  mb_\* functions, so in php <=5.5 it will work wrongly, if i don't personally call/set mb_internal_encoding('UTF-8'). It should be at least document, better, it shouldn't be required at all and should just work. However, the pull request should add test only for <=5.5 and not change encoding manually.

**Comment by hranicka** [comment]
I've removed `mb_internal_encoding` call from tests and replaced with Travis builds.

Here are test results: https://github.com/hranicka/inflection/branches

(master = this PR; demo/utf8issue = code before the PR)

**Comment by hranicka** [comment]
@Mikulas Thank you! I've replaced unnecessary mbstring functions.

And made another change b8a0883. Is it OK?

Just before the fix, new test case failed. Now that case seems OK.

**Comment by Mikulas** [comment]
:+1: Alright, thanks, merging.

**Pull request closed without merging**
